// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppendPath(arg1:string,arg2:string):Promise<string>;

export function CopyEntries(arg1:string,arg2:string):Promise<void>;

export function DeleteEntries(arg1:string):Promise<void>;

export function DirExists(arg1:string):Promise<boolean>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetClip():Promise<string>;

export function GetCopyClip(arg1:string):Promise<string>;

export function GetEnv(arg1:string):Promise<string>;

export function GetEnvironment():Promise<Array<string>>;

export function GetError():Promise<string>;

export function GetExecutable():Promise<string>;

export function GetFeedback(arg1:string,arg2:string):Promise<string>;

export function GetHomeDir():Promise<string>;

export function GetOSName():Promise<string>;

export function Getwd():Promise<string>;

export function MakeDir(arg1:string):Promise<void>;

export function MakeFile(arg1:string):Promise<void>;

export function MoveEntries(arg1:string,arg2:string):Promise<void>;

export function Quit():Promise<void>;

export function ReadDir(arg1:string):Promise<Array<main.FileInfo>>;

export function ReadFile(arg1:string):Promise<string>;

export function RenameEntry(arg1:string,arg2:string):Promise<void>;

export function RunCommandLine(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:string):Promise<string>;

export function SetClip(arg1:string):Promise<void>;

export function SplitFile(arg1:string):Promise<main.FileParts>;

export function SystemOpenFile(arg1:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
