// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendPath(arg1, arg2) {
  return window['go']['main']['App']['AppendPath'](arg1, arg2);
}

export function Chmod(arg1, arg2) {
  return window['go']['main']['App']['Chmod'](arg1, arg2);
}

export function CopyEntries(arg1, arg2) {
  return window['go']['main']['App']['CopyEntries'](arg1, arg2);
}

export function CreateTempFile(arg1) {
  return window['go']['main']['App']['CreateTempFile'](arg1);
}

export function DeleteEntries(arg1) {
  return window['go']['main']['App']['DeleteEntries'](arg1);
}

export function DirExists(arg1) {
  return window['go']['main']['App']['DirExists'](arg1);
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function GetClip() {
  return window['go']['main']['App']['GetClip']();
}

export function GetCopyClip(arg1) {
  return window['go']['main']['App']['GetCopyClip'](arg1);
}

export function GetEnv(arg1) {
  return window['go']['main']['App']['GetEnv'](arg1);
}

export function GetEnvironment() {
  return window['go']['main']['App']['GetEnvironment']();
}

export function GetError() {
  return window['go']['main']['App']['GetError']();
}

export function GetExecutable() {
  return window['go']['main']['App']['GetExecutable']();
}

export function GetFeedback(arg1, arg2) {
  return window['go']['main']['App']['GetFeedback'](arg1, arg2);
}

export function GetGitHubScripts() {
  return window['go']['main']['App']['GetGitHubScripts']();
}

export function GetGitHubThemes() {
  return window['go']['main']['App']['GetGitHubThemes']();
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetOSName() {
  return window['go']['main']['App']['GetOSName']();
}

export function Getwd() {
  return window['go']['main']['App']['Getwd']();
}

export function MakeDir(arg1) {
  return window['go']['main']['App']['MakeDir'](arg1);
}

export function MakeFile(arg1) {
  return window['go']['main']['App']['MakeFile'](arg1);
}

export function MoveEntries(arg1, arg2) {
  return window['go']['main']['App']['MoveEntries'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadDir(arg1) {
  return window['go']['main']['App']['ReadDir'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RenameEntry(arg1, arg2) {
  return window['go']['main']['App']['RenameEntry'](arg1, arg2);
}

export function RunCommandLine(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunCommandLine'](arg1, arg2, arg3, arg4);
}

export function SendEmail(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['SendEmail'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function SetClip(arg1) {
  return window['go']['main']['App']['SetClip'](arg1);
}

export function SplitFile(arg1) {
  return window['go']['main']['App']['SplitFile'](arg1);
}

export function SystemOpenFile(arg1) {
  return window['go']['main']['App']['SystemOpenFile'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
